# Generated by Django 3.0.3 on 2020-02-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorProductes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estanterias',
            name='pasillo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buscadorProductes.Pasillos'),
        ),
        migrations.AddField(
            model_name='localilizacionactualprod',
            name='estanteria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buscadorProductes.Estanterias'),
        ),
        migrations.AddField(
            model_name='localilizacionactualprod',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buscadorProductes.Producto'),
        ),
    ]
