# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorProductes', '0002_auto_20200223_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='EAN',
            field=models.CharField(max_length=13),
        ),
    ]
