# Generated by Django 3.0.3 on 2020-03-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorProductes', '0003_auto_20200223_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='estanterias',
            old_name='pasillo',
            new_name='n_pasillo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nom',
            new_name='descipcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=None, max_length=140),
        ),
        migrations.AddField(
            model_name='estanterias',
            name='n_almacen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buscadorProductes.Almacen'),
        ),
    ]
