# Generated by Django 3.0.3 on 2020-03-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorProductes', '0006_auto_20200306_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
