# Generated by Django 3.0.3 on 2020-03-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorProductes', '0008_auto_20200306_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
    ]
