# Generated by Django 3.0.3 on 2020-03-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorProductes', '0010_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localilizacionactualprod',
            name='producto',
        ),
    ]
