# Generated by Django 3.0.3 on 2020-03-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorProductes', '0011_remove_localilizacionactualprod_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='localilizacionactualprod',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buscadorProductes.Producto'),
        ),
    ]
