# Generated by Django 3.0.3 on 2020-03-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorProductes', '0002_producto_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descipcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('E', 'Disponible'), ('D', 'No Disponiible')], default='E', max_length=1),
        ),
    ]
